/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package retail.ui;

import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author Amikom
 */
public class FrmMain extends javax.swing.JFrame {

    /**
     * Creates new form FrmMain
     */
    public FrmMain() {
        initComponents();
        this.setExtendedState(this.getExtendedState()| JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnFile = new javax.swing.JMenu();
        mnItemExit = new javax.swing.JMenuItem();
        mnDataMaster = new javax.swing.JMenu();
        mnItemBarang = new javax.swing.JMenuItem();
        mnItemSupplier = new javax.swing.JMenuItem();
        mnDataTransaksi = new javax.swing.JMenu();
        mnItemTransaksiJual = new javax.swing.JMenuItem();
        mnItemTransaksiBeli = new javax.swing.JMenuItem();
        mnLaporanPenjualan = new javax.swing.JMenuItem();
        mnLaporanPembelian = new javax.swing.JMenuItem();
        mnAbout = new javax.swing.JMenu();
        mnItemCara = new javax.swing.JMenuItem();
        mnItemTentang = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        mnFile.setText("File");

        mnItemExit.setText("Exit");
        mnFile.add(mnItemExit);

        jMenuBar1.add(mnFile);

        mnDataMaster.setText("Data Master");

        mnItemBarang.setText("Data Barang");
        mnItemBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemBarangActionPerformed(evt);
            }
        });
        mnDataMaster.add(mnItemBarang);

        mnItemSupplier.setText("Data Supplier");
        mnItemSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemSupplierActionPerformed(evt);
            }
        });
        mnDataMaster.add(mnItemSupplier);

        jMenuBar1.add(mnDataMaster);

        mnDataTransaksi.setText("Transaksi");

        mnItemTransaksiJual.setText("Transaksi Penjualan");
        mnItemTransaksiJual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemTransaksiJualActionPerformed(evt);
            }
        });
        mnDataTransaksi.add(mnItemTransaksiJual);

        mnItemTransaksiBeli.setText("Transaksi Pembelian");
        mnItemTransaksiBeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemTransaksiBeliActionPerformed(evt);
            }
        });
        mnDataTransaksi.add(mnItemTransaksiBeli);

        mnLaporanPenjualan.setText("Laporan Penjualan");
        mnLaporanPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLaporanPenjualanActionPerformed(evt);
            }
        });
        mnDataTransaksi.add(mnLaporanPenjualan);

        mnLaporanPembelian.setText("Laporan Pembelian");
        mnLaporanPembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLaporanPembelianActionPerformed(evt);
            }
        });
        mnDataTransaksi.add(mnLaporanPembelian);

        jMenuBar1.add(mnDataTransaksi);

        mnAbout.setText("About");

        mnItemCara.setText("Cara Penggunaan");
        mnAbout.add(mnItemCara);

        mnItemTentang.setText("Tentang Pengembang");
        mnAbout.add(mnItemTentang);

        jMenuBar1.add(mnAbout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private FrmBarang barang;
    private void mnItemBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemBarangActionPerformed
        // TODO add your handling code here:
        if (barang == null || barang.isVisible() == false) {
            barang = new FrmBarang();
            desktopPane.add(barang);
        }
        barang.setVisible(true);
        barang.moveToFront();
        try {
            barang.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnItemBarangActionPerformed
FrmSupplier supplier;
    private void mnItemSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemSupplierActionPerformed
        // TODO add your handling code here:
        
        if (supplier == null || supplier.isVisible() == false) {
            supplier = new FrmSupplier();
            desktopPane.add(supplier);
        }
        supplier.setVisible(true);
        supplier.moveToFront();
        try {
            supplier.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnItemSupplierActionPerformed
FrmTransaksiPembelian pembelian;
    private void mnItemTransaksiBeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemTransaksiBeliActionPerformed
        // TODO add your handling code here:
        
        if (pembelian == null || pembelian.isVisible() == false) {
            pembelian = new FrmTransaksiPembelian();
            desktopPane.add(pembelian);
        }
        pembelian.setVisible(true);
        pembelian.moveToFront();
        try {
            pembelian.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnItemTransaksiBeliActionPerformed

    FrmTransaksiPenjualan penjualan;
    private void mnItemTransaksiJualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemTransaksiJualActionPerformed
        // TODO add your handling code here:
        
        if (penjualan == null || penjualan.isVisible() == false) {
            penjualan = new FrmTransaksiPenjualan();
            desktopPane.add(penjualan);
        }
        penjualan.setVisible(true);
        penjualan.moveToFront();
        try {
            penjualan.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnItemTransaksiJualActionPerformed
    
    FrmLaporanTransaksiPembelian lBeli;
    private void mnLaporanPembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLaporanPembelianActionPerformed
        // TODO add your handling code here:
        if (lBeli == null || lBeli.isVisible() == false) {
            lBeli = new FrmLaporanTransaksiPembelian();
            desktopPane.add(lBeli);
        }
        lBeli.setVisible(true);
        lBeli.moveToFront();
        try {
            lBeli.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnLaporanPembelianActionPerformed

    FrmLaporanTransaksiPenjualan lJual;
    private void mnLaporanPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLaporanPenjualanActionPerformed
        // TODO add your handling code here:
        if (lJual == null || lJual.isVisible() == false) {
            lJual = new FrmLaporanTransaksiPenjualan();
            desktopPane.add(lJual);
        }
        lJual.setVisible(true);
        lJual.moveToFront();
        try {
            lJual.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnLaporanPenjualanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mnAbout;
    private javax.swing.JMenu mnDataMaster;
    private javax.swing.JMenu mnDataTransaksi;
    private javax.swing.JMenu mnFile;
    private javax.swing.JMenuItem mnItemBarang;
    private javax.swing.JMenuItem mnItemCara;
    private javax.swing.JMenuItem mnItemExit;
    private javax.swing.JMenuItem mnItemSupplier;
    private javax.swing.JMenuItem mnItemTentang;
    private javax.swing.JMenuItem mnItemTransaksiBeli;
    private javax.swing.JMenuItem mnItemTransaksiJual;
    private javax.swing.JMenuItem mnLaporanPembelian;
    private javax.swing.JMenuItem mnLaporanPenjualan;
    // End of variables declaration//GEN-END:variables
}
