/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package retail.ui;

import java.net.MalformedURLException;
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import retail.config.Config;
import retail.dao.api.IBarangDao;
import retail.dao.api.ISupplierDao;
import retail.model.Barang;
import retail.model.Supplier;

/**
 *
 * @author Amikom
 */
public class FrmSupplier extends javax.swing.JInternalFrame {
    private final Object[] columnNames = {"No","Kode",
                                "Nama","Alamat"};
    
    private final DefaultTableModel tableModel = new DefaultTableModel();
    private List<Supplier> recordSupplier = new ArrayList<>();
    private ISupplierDao supplierDao = null;
    private boolean isTambahData = true;
    /**
     * Creates new form FrmSupplier
     */
    public FrmSupplier() {
        initComponents();
        initTable();
        initSupplierDao();
        loadSupplier();
    }

    private void initTable(){
        tableModel.setColumnIdentifiers(columnNames);
        tblSupplier.setModel(tableModel);
        tblSupplier.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }
        
    private void initSupplierDao(){
        String url = "rmi://"+ Config.ip_server + ":1099/supplierDao";
        try {
            supplierDao = (ISupplierDao) Naming.lookup(url);
        } catch (NotBoundException ex) {
            Logger.getLogger(FrmBarang.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MalformedURLException ex) {
            Logger.getLogger(FrmBarang.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            JOptionPane.showMessageDialog(null,"Koneksi ke service "+url+"[Gagal]: cek kembali aplikasi server", "Peringatan", JOptionPane.WARNING_MESSAGE);
        }
    }
    
    private void loadSupplier() {
        try {
            // reset data di tabel
            tableModel.setRowCount(0);
            // mengambil data supplier dari server
            // kemudian menyimpannya ke objek list
            recordSupplier = supplierDao.getAll();
            // ekstrak data supplier yg ada di dalam objek list
            // kemudian menampilkannya ke objek tabel
            for (Supplier supplier : recordSupplier) {
                fillToTable(true, supplier);
            }
        } catch (RemoteException ex) {
        Logger.getLogger(FrmSupplier.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void loadRecordSupplierByName(String namaSupplier) {
        try {
            // reset data di tabel
            tableModel.setRowCount(0);
            // mengambil data supplier dari server
            // kemudian menyimpannya ke objek list
            recordSupplier = supplierDao.getByName(namaSupplier);
            // ekstrak data supplier yg ada di dalam objek list
            // kemudian menampilkannya ke objek tabel
            for (Supplier supplier : recordSupplier) {
                fillToTable(true, supplier);
            }
        } catch (RemoteException ex) {
            Logger.getLogger(FrmSupplier.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    // method untuk menampilkan data supplier ke tabel
private void fillToTable(boolean isTambahData, Supplier supplier){
    if (isTambahData) { // data baru
        // ambil nomor urut terakhir
        int noUrut = tableModel.getRowCount() + 1;
        Object[] objects = new Object[columnNames.length];
        objects[0] = noUrut;
        objects[1] = supplier.getKodeSupplier();
        objects[2] = supplier.getNamaSupplier();
        objects[3] = supplier.getAlamat();
        // tambahkan data supplier ke dalam tabel
        tableModel.addRow(objects);
    } else { // edit data
        // ambil nilai baris yang dipilih
        int row = tblSupplier.getSelectedRow();
        // update data supplier yg ada di tabel
        tableModel.setValueAt(supplier.getKodeSupplier(), row, 1);
        tableModel.setValueAt(supplier.getNamaSupplier(), row, 2);
        tableModel.setValueAt(supplier.getAlamat(), row, 3);
    }
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frmAddEditSupplier = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtKode = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtAlamat = new javax.swing.JTextField();
        btnSelesai = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnPerbaiki = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSupplier = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnCari = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtCari = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();

        jLabel2.setText("Kode Supplier");

        jLabel3.setText("Nama Supplier");

        jLabel4.setText("Alamat");

        btnSelesai.setText("Selesai");
        btnSelesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelesaiActionPerformed(evt);
            }
        });

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frmAddEditSupplierLayout = new javax.swing.GroupLayout(frmAddEditSupplier.getContentPane());
        frmAddEditSupplier.getContentPane().setLayout(frmAddEditSupplierLayout);
        frmAddEditSupplierLayout.setHorizontalGroup(
            frmAddEditSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmAddEditSupplierLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frmAddEditSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frmAddEditSupplierLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(frmAddEditSupplierLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frmAddEditSupplierLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtKode, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frmAddEditSupplierLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSimpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSelesai)))
                .addContainerGap())
        );
        frmAddEditSupplierLayout.setVerticalGroup(
            frmAddEditSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmAddEditSupplierLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frmAddEditSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(frmAddEditSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(frmAddEditSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frmAddEditSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSelesai)
                    .addComponent(btnSimpan))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setClosable(true);

        btnPerbaiki.setText("Perbaiki");
        btnPerbaiki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerbaikiActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        tblSupplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblSupplier);

        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        jLabel1.setText("Nama Supplier");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtCari)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCari)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnCari))
                .addContainerGap())
        );

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnTambah)
                        .addGap(18, 18, 18)
                        .addComponent(btnPerbaiki)
                        .addGap(18, 18, 18)
                        .addComponent(btnHapus)
                        .addGap(0, 135, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah)
                    .addComponent(btnPerbaiki)
                    .addComponent(btnHapus))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPerbaikiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerbaikiActionPerformed
        // TODO add your handling code here:
        int row = tblSupplier.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this,"Data Supplier belum dipilih",
                "Peringatan",JOptionPane.WARNING_MESSAGE);
        }else{
            isTambahData = false;
            Supplier supplier = recordSupplier.get(row);

            txtKode.setText(supplier.getKodeSupplier());
            txtNama.setText(supplier.getNamaSupplier());
            txtAlamat.setText(supplier.getAlamat());

            txtKode.setEnabled(false);
            txtNama.requestFocus();

            frmAddEditSupplier.pack();
            frmAddEditSupplier.setLocationRelativeTo(this);
            frmAddEditSupplier.setModal(true);
            frmAddEditSupplier.setVisible(true);
        }
    }//GEN-LAST:event_btnPerbaikiActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        int row = tblSupplier.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this,"Data Barang belum dipilih",
                "Peringatan",JOptionPane.WARNING_MESSAGE);
        }else{
            Supplier supplier = recordSupplier.get(row);
            int result=JOptionPane.showConfirmDialog(this,
                "Apakah data supplier '"+supplier.getNamaSupplier()+"' Ingin dihapus?",
                "Konfirmasi",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);

            if (result == JOptionPane.YES_OPTION) {
                try {
                    result = supplierDao.delete(supplier);
                    if (result > 0) {
                        tableModel.removeRow(row);
                        recordSupplier.remove(supplier);
                    }
                } catch (RemoteException ex) {
                    Logger.getLogger(FrmBarang.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        loadRecordSupplierByName(txtCari.getText());
    }//GEN-LAST:event_btnCariActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        isTambahData = true;
        txtKode.setText("");
        txtNama.setText("");
        txtAlamat.setText("");

        txtKode.setEnabled(true);
        txtKode.requestFocus();

        frmAddEditSupplier.pack();
        frmAddEditSupplier.setLocationRelativeTo(this);
        frmAddEditSupplier.setModal(true);
        frmAddEditSupplier.setVisible(true);
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        Supplier supplier = new Supplier();
        supplier.setKodeSupplier(txtKode.getText());
        supplier.setNamaSupplier(txtNama.getText());
        supplier.setAlamat(txtAlamat.getText());
        try {
            int hasil = 0;
            if (isTambahData) { // input data baru
                hasil = supplierDao.save(supplier);
                if (hasil > 0) {
                    // tampilkan pesan berhasil
                    JOptionPane.showMessageDialog(frmAddEditSupplier, "Data supplier berhasil disimpan","Informasi", JOptionPane.INFORMATION_MESSAGE);
                    // tambahkan data barang ke tabel
                    fillToTable(isTambahData, supplier);
                    // tambahkan data barang ke list
                    recordSupplier.add(supplier);
                    // reset form input
                    txtKode.setText("");
                    txtNama.setText("");
                    txtAlamat.setText("");
                    txtKode.requestFocus();
                }
            } else { // update data yg sudah ada
                hasil = supplierDao.update(supplier);
                if (hasil > 0) {
                    // tampilkan pesan berhasil
                    JOptionPane.showMessageDialog(frmAddEditSupplier, "Data barang berhasil disimpan","Informasi", JOptionPane.INFORMATION_MESSAGE);
                    // update data barang yang ada di tabel
                    fillToTable(isTambahData, supplier);
                    // ambil baris barang yang diperbaiki
                    int row = tblSupplier.getSelectedRow();
                    // update data barang yang ada di list
                    recordSupplier.set(row, supplier);
                    // tutup dialog edit data
                    frmAddEditSupplier.setVisible(false);
                }
            }
        } catch (RemoteException ex) {
            Logger.getLogger(FrmBarang.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnSelesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelesaiActionPerformed
        // TODO add your handling code here:
        frmAddEditSupplier.setVisible(false);
    }//GEN-LAST:event_btnSelesaiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnPerbaiki;
    private javax.swing.JButton btnSelesai;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JDialog frmAddEditSupplier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSupplier;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtKode;
    private javax.swing.JTextField txtNama;
    // End of variables declaration//GEN-END:variables
}
